Added "recipes" section to the book with initial panic handler sample
godot-rust/gdnative-book pull request #26
Opened 2021-05-21 01:29 UTC by jacobsky

Included the rust_panic_handler recipe that was graciously provided by setzer22 in discord.

This is a second draft of the panic handler. I initially chose the name "recipes" as a reference to the [Kids can Code - Godot Recipes](https://kidscancode.org/godot_recipes/) website, but I would be happy to change the name to something if recipes has the wrong connotations.

Any and all feedback would be welcome.

2021-05-21 07:23 UTC, Bromeon requested changes
Thanks a lot for your contribution! I haven't tested the code or rendered the markdown yet, so my feedback is mostly about language.

Capitalization should be done consistently, and in the way the products refer to themselves:
* godot-rust (this one should be already correct here)
* Godot
* Rust
* GDScript
* GDNative

2021-05-21 07:23 UTC, Bromeon commented on src/recipes.md
> +These recipes are for general-use cases and are not intended to be the *only* way to implement these patterns. Each recipe should be evaluated and customized to your specific use-case.
I think it's "use case" (no hyphen) and thus also "general use cases".

2021-05-21 07:23 UTC, Bromeon commented on src/recipes/rust_panic_handler.md
> +This recipe was written and tested with godot-rust 0.9.3 with rust version rust 1.52.1
2nd line should be `Rust version 1.52.1` (uppercase, no repetition)

2021-05-21 07:23 UTC, Bromeon commented on src/recipes/rust_panic_handler.md
> +First create a gdscript with the following code named "rust_panic_hook.gd"
"GDScript"

2021-05-21 07:23 UTC, Bromeon commented on src/recipes/rust_panic_handler.md
> +	assert(false, error_msg)
Should we maybe qualify the types?
``` 
func rust_panic_dbg_hook(error_msg: String) -> void:
    assert(false, error_msg)
```

Also, maybe it should be called just "rust_panic_hook"?
The "dbg" suggests this is only active in debug mode, like `debug_assert`.

2021-05-21 07:23 UTC, Bromeon commented on src/recipes/rust_panic_handler.md
> +In the Project Settings -> Autoload menu, create an autoload singleton referencing the script (in this case "rust_panic_hook.gd).
Unnecessary quote

2021-05-21 07:23 UTC, Bromeon commented on src/recipes/rust_panic_handler.md
> +    init_panic_hook()
Missing semicolon -- I know it's a void return type, but I think it's still good practice as this looks like you want to return the value of `init_panic_hook()`.

2021-05-21 07:23 UTC, Bromeon commented on src/recipes/rust_panic_handler.md
> +Now you can run your game and once it is fully initialized any panics will be pause the game execution and print the panic message in Godot's editor in the Debugger's Error tab.
"once it is fully initialized, any panics will pause..."
(comma + without "be")

2021-05-21 07:23 UTC, Bromeon commented on src/recipes/rust_panic_handler.md
> +        let error_message;
Could use an empty line before a new variable declaration (whose initialization spans multiple lines), but that's really nitpicking 🙂

2021-05-21 10:01 UTC, jacobsky commented
@Bromeon I've gone ahead and made the changes as mentioned. Thank you for taking a look. I've tested the above code in the mkbook serve and I didn't see any artifacts due to formatting. Please let me know if you have any additional changes that you could like to see.

2021-05-21 10:01 UTC, jacobsky commented
Unfortunately, I just pulled the code directly from my own project, so while I have tested that it works, I don't have a simple project that you can run to verify the sample code.

2021-05-23 07:18 UTC, toasteater commented on src/recipes.md
> +- [Rust Panic Handler](./recipes/rust_panic_handler.md) is a recipe that enables getting Rust panic information inside the Godot editor.
You don't have to enumerate the recipes here since mdbook will automatically generate a table of contents in the side bar from`SUMMARY.md`. Live example: https://godot-rust.github.io/book/

2021-05-23 07:18 UTC, toasteater commented on src/recipes/rust_panic_handler.md
> +When using GDNative, rust panics are ignored by Godot by default. This recipe can be used to catch those panics in the Godot editor at runtime.
Missed capitalization change: Rust

2021-05-24 04:27 UTC, jacobsky commented on src/recipes.md
> +- [Rust Panic Handler](./recipes/rust_panic_handler.md) is a recipe that enables getting Rust panic information inside the Godot editor.
That's great to know!I'll go ahead and fix that

2021-05-24 09:07 UTC, jacobsky commented
Pushed a fix for the additional feedback.

2021-05-24 10:28 UTC, toasteater approved these changes
Looks good to me! @Bromeon Do you have any additional concerns?

2021-05-24 12:08 UTC, Bromeon reviewed
Mostly good, just minor nitpicks 🙂 

Maybe @setzer22, who was involved in the idea, can have a quick look over it?

2021-05-24 12:08 UTC, Bromeon commented on src/recipes/rust_panic_handler.md
> +4. Prints the error message and optionally the backtrace inforamtion
"information" typo

I would also be consistent with punctuation.
The "The above code does the following" should end with `:`, and each line should have end without full-stop, as it's not really a sentence (but I'm also OK with full-stop everywhere).

Maybe don't use the 3rd person -- thus "Get the default panic hook", "Print the error message..." etc.

2021-05-24 12:08 UTC, Bromeon commented on src/recipes/rust_panic_handler.md
> +    // a version of rust where backtrace is included in the standard library (e.g. Rust nightly as of the date of publishing)
"Cargo.toml" and "Rust" (capital)

Some commas might make the long sentence a bit easier to understand:

> To enable backtrace, you will need the `backtrace` crate to be included in your Cargo.toml, or ...

2021-05-24 23:43 UTC, jacobsky commented
Thank you for the feedback/editing @Bromeon and @toasteater !

I addressed the feedback in the previous commit.

2021-05-25 07:29 UTC, toasteater commented
setzer doesn't seem to be very active on GitHub so I doubt he's going to see the ping. What's written here looks good enough to me now, and I'm willing to trust jacobsky's statement that the code works, so I'm merging this for now. Thanks for the PR!

2021-05-25 07:30 UTC, merged

2021-05-25 08:39 UTC, jacobsky commented
Thank you for the reviews! It was a fun project to work on :)

2021-05-25 16:51 UTC, setzer22 commented
Just saw the ping :sweat_smile: I like how the section turned out. I'll be sure to get this new improved version in my projects from now on! Thanks for working on this :+1: