Updated the FAQ and changed some of the formatting.
godot-rust/gdnative-book pull request #33
Opened 2021-09-06 02:05 UTC by jacobsky

@Bromeon As I mentioned via discord, I went through the issues and extrapolated on cleaned up the FAQ a bit.
Also added a fix to have the logging recipe get added to the summary as it was previously missing.

2021-09-06 16:20 UTC, Bromeon reviewed
Thank you very much, your changes add some extremely valuable insights 👍🏼 

I tried to be quite open about my thoughts, so expect lots of comments 🙂

In cases where I added code or text, it can make sense if you use the "Quote comment" function to get the original formatting -- this is especially true for links within this repo, which are sugared by GitHub. Also feel free to copy-paste anything verbatim.

Some general consistency remarks: maybe check the capitalization of a few keywords -- `Rust`, `Godot`, `godot-rust`, `GDNative`, `GDScript`. At some point in the distant future I might add CI checks for those 😛

2021-09-06 16:20 UTC, Bromeon commented on src/faq/code-faq.md
> +## Avoiding a `BorrowFailed` error on method call
This should be removed.

2021-09-06 16:20 UTC, Bromeon commented on src/faq/code-faq.md
> +1. Godot objects can be accessed and aliased freely but Rust's &mut expects only a single mutable alias at a time. In terms of type "safety" there is no specific type safety. We are aware that this m
It's not very clear to me what you mean with this bullet point (the last sentence is incomplete). If it's about reduced type safety, I would probably mention it last.

To me the main message is along the following lines -- you already mention that in points 2 and 3, so those are good as-is:

> `&mut` means that only one reference can exist simultaneously (no aliasing), _not_ that the object is mutable. Mutability is often a _consequence_ of the exclusiveness. Since Godot objects are managed by the engine, Rust cannot guarantee that references are exclusive, as such using `&mut` would cause undefined behavior. Instead, an interior mutability pattern based on `&T` is used.

Maybe we can link again to https://docs.rs/dtolnay/latest/dtolnay/macro._02__reference_types.html (here with `latest` instead of a version)?

2021-09-06 16:20 UTC, Bromeon commented on src/faq/code-faq.md
> +Longer Answer: Most of the use of the `unsafe` keyword is related to working with the scene tree as well as working with the Godot libraries. This is due to the lack of static analysis over the engin
To me, the longer answer seems a bit abstract and doesn't really answer more than the short one. What would be interesting to mention is that a lot of `unsafe` exists primarily because of:
* **Object lifetimes:** Godot manages memory of objects independently of Rust. This means that Rust references can be invalidated when Godot destroys referred-to objects. This usually happens due to bugs in GDScript code, like calling `free()`/`queue_free()` of something actively in use.
* **Thread safety:** while Rust has a type system to ensure thread safety statically (`Send`, `Sync`), such mechanisms do not exist in either GDScript or C++. Even user-defined GDScript code has direct access to [`Thread`](https://docs.godotengine.org/en/stable/classes/class_thread.html) API.
* _other reasons?_

You can copy-paste this as-is, if you want.

2021-09-06 16:20 UTC, Bromeon commented on src/faq/code-faq.md
> +    // This is safe because
"safe because **the code panics if the expected value is not present**"

2021-09-06 16:20 UTC, Bromeon commented on src/faq/code-faq.md
> +    // It is up to the programmer to ensure that this function call will not result in undefined behavior.
The existence of the function is not the reason why `call()` is unsafe; that wouldn't result in UB, just a Godot runtime error.

The reason why `call()` is unsafe is because it can invoke functions that directly manipulate memory (`Object.free()`, `Reference.unreference()`, ...) as well as other native code which is not safe.

2021-09-06 16:20 UTC, Bromeon commented on src/faq/code-faq.md
> +Unfortunately this is currently a general limitation of GDNative (see [related issue](https://github.com/godotengine/godot/issues/23260)).
I would start with "No" to make it very clear 🙂

2021-09-06 16:20 UTC, Bromeon commented on src/faq/code-faq.md
> +This is another limitation of GDNative -- static methods are not supported in general.
Duplicate sentence

2021-09-06 16:20 UTC, Bromeon commented on src/faq/code-faq.md
> +
Maybe add:

> Direct access to such properties is planned in https://github.com/godot-rust/godot-rust/issues/689.

2021-09-06 16:20 UTC, Bromeon commented on src/faq/code-faq.md
> +    Returns a resource from the filesystem that is loaded during script parsing. (emphasis mine)
I miss the emphasis 🙂 

Also, would it make sense to have the whole sentence as italics (to suggest quote) and the emphasis additionally in bold?

2021-09-06 16:20 UTC, Bromeon commented on src/faq/code-faq.md
> +```swift
Does Swift have similar syntax highlighting? Or do we want to add ` ```gdscript ` and hope that `mdbook` will support it one day?

GitHub already supports it, which is very nice:
```gdscript
extends Node
class_name MyClass
var node

func _ready():
  node = Node.new()
  self.add_child(node, false)
```

2021-09-06 16:20 UTC, Bromeon commented on src/faq/code-faq.md
> +    // It should also be possible to create an null `Ref<Node>` but
I'm actually not sure if null refs are possible, or already checked at the marshalling layer.
If we did `my_ref.assume_safe()` and then dereference the `TRef`, things would explode.

As such, I would directly suggest the `Option<Ref<Node>>`.

2021-09-06 16:20 UTC, Bromeon commented on src/faq/configuration-faq.md
> +[general]
`[general]` should probably be one line further down, to make clear it belongs to the config options below.

2021-09-06 16:20 UTC, Bromeon commented on src/faq/configuration-faq.md
> +5. For each desired target, select a path to the location of the library created by cargo.
Few things:
* Missing colon: "In the editor: from the editor, ..."
* In my version the point is called `New Resource...`, not `Create New Resource`, is this different for you?
* Please use `GDNativeLibrary` everywhere, I think different capitalization/spacing can confuse people here
* Maybe in point 3 we should mention: "The typical file extension for libraries is .gdnlib." -- It is referred to further down in the FAQ.

2021-09-06 16:20 UTC, Bromeon commented on src/faq/configuration-faq.md
> +2. Created manually by create a .gdns file with the following code snippet
2. Manually by **creating** a .gdns file with the following code snippet:

2021-09-06 16:20 UTC, Bromeon commented on src/faq/configuration-faq.md
> +Can I use rust as a toolscript?
"Rust"

Maybe also link to the Godot page:

> Can I use Rust as a [tool script](https://docs.godotengine.org/en/stable/tutorials/misc/running_code_in_the_editor.html)?

2021-09-06 16:20 UTC, Bromeon commented on src/faq/configuration-faq.md
> +For example, in the case where a
incomplete

2021-09-06 16:20 UTC, Bromeon commented on src/faq/configuration-faq.md
> +> If your tool classes inherit `EditorPlugin`, `EditorImportPlugin` or other extensions, it is required that you set `reloadable = false` in the gdnative library where the tool class is defined.
Incomplete sentence; not really sure where the "considerations" belong or why they're formatted like this?

2021-09-06 16:20 UTC, Bromeon commented on src/faq/configuration-faq.md
> +Yes. You can create as many libraries as you need for your project. Do be mindful that it is possible for name collision to occur when loading from multiple dynamic libraries. This can occur in the e
Good that you explain this, it's a little-known feature. Although while possible, there's usually no good reason to use multiple libraries. I would also explain that the recommended way is to have 1 .gdnlib and many .gdns files.

2021-09-06 16:20 UTC, Bromeon commented on src/faq/help-faq.md
> +# Help FAQ
Maybe name this chapter "Community"? It's not only about help but also about interacting with the community and contributing.

2021-09-06 16:20 UTC, Bromeon commented on src/faq/help-faq.md
> +- [NativeClass](https://docs.rs/gdnative/0.9.3/gdnative/derive.NativeClass.html) includes all the derive macro attributes that you can use to integrate your script class with godot.
* "the following:"
* Also mention the book, I would even do so as first bullet point.
* Can you replace `0.9.3` with `latest`? Then the FAQ doesn't become outdated as we release new versions.
* Maybe `GodotObject` and `NativeClass` as sub-bulletpoints of `API documentation` (i.e. indented one level).

2021-09-06 16:20 UTC, Bromeon commented on src/faq/meta-faq.md
> +godot-rust follows the [semantic versioning](https://semver.org/) for the API breaking changes.
Rust semver is slightly different, I would link to this instead: https://doc.rust-lang.org/cargo/reference/semver.html

2021-09-06 16:20 UTC, Bromeon commented on src/faq/meta-faq.md
> +The longer answer is that due the goal of the bindings is to ease the friction between using Rust and interacting with the Godot API. This is accomplished by use of Procedural Macros as well as cleve
"The longer answer is that ~due~ the goal"

2021-09-06 16:20 UTC, Bromeon commented on src/faq/meta-faq.md
> +In the case of primitive types, to avoid the runtime overhead of the FFI effort has been made to write conversions between a select number of Godot types to have a Rust native type, but in most cases
This sentence is quite long and still rather vague -- I would instead mention something like:

> Types, which are not part of Godot's `Object` class hierarchy, have an implementation in Rust. This avoids FFI overhead and allows code to be more idiomatic. Examples are `Vector2`, `Vector3`, `Color`, `GodotString`, `Dictionary`, etc.

2021-09-06 16:20 UTC, Bromeon commented on src/faq/multithreading-faq.md
> +Follow godot's thread safety guidelines and change your settings to "Multi-threaded" in "Project Settings > Rendering > Threading".
"Godot's thread safety guidelines" could link to https://docs.godotengine.org/en/stable/tutorials/threads/index.html.

2021-09-06 16:20 UTC, Bromeon commented on src/faq/multithreading-faq.md
> +There are a few potential things that can slow down server usage
full-stop or colon

2021-09-06 16:20 UTC, Bromeon commented on src/faq/multithreading-faq.md
> +Multi-threading with Servers would require that you manually create a threadpool that can hold the reference to the Server. Additional testing is required to ensure that this is an actual optimizatio
This explanation is absolutely awesome 👍🏼 
Very valuable insights that would need a long time to figure out.

2021-09-06 16:20 UTC, Bromeon commented on src/faq/multithreading-faq.md
> +## Why do I get DifferentThread when calling my code from multiple threads?
maybe "`DifferentThread` error"

2021-09-06 16:20 UTC, Bromeon commented on src/faq/tooling-faq.md
> +As of writing, WASM targets are a tenatively doable, but it requires additional configuration and is currently not supported out of the box. This godot-rust bindings do not officially support this ta
"tentatively" and "The godot-rust bindings"

I would add:
> The progress in this regard can be tracked in https://github.com/godot-rust/godot-rust/issues/647.

2021-09-06 16:20 UTC, Bromeon commented on src/faq/tooling-faq.md
> +##  What about performance? Is this binding speed up final Godot build?
Maybe "Does this binding speed up my game in Godot"?

2021-09-06 16:20 UTC, Bromeon commented on src/faq/tooling-faq.md
> +Caveat: The above apply only to release builds with appropriate release settings. When comparing to debug builds in Rust are very, very slow.
"Debug builds in Rust can be very slow".

I think it also depends what one is doing, so I would write it less absolute.

2021-09-06 16:20 UTC, Bromeon commented on src/faq/tooling-faq.md
> +Caveat 2: It is still possible to write rust code that has poor performance. You will still need to be mindful of the specific algorithms that you are choosing.
> Caveat 3: A lot of code in a game is not performance-critical and as such, Rust will help only in limited ways. When deciding between GDScript and Rust, you should also consider other factors such as static type safety, scalability, ecosystem and prototyping speed. Try to use the best of both worlds, it's very well possible to have part of your code in GDScript and part in Rust.

2021-09-07 01:05 UTC, jacobsky commented on src/faq/code-faq.md
> +## Avoiding a `BorrowFailed` error on method call
Oops! Good catch!

2021-09-07 01:11 UTC, jacobsky commented on src/faq/code-faq.md
> +1. Godot objects can be accessed and aliased freely but Rust's &mut expects only a single mutable alias at a time. In terms of type "safety" there is no specific type safety. We are aware that this m
I like that phrasing much better, I'll go ahead and put that in the faq.

2021-09-07 01:20 UTC, jacobsky commented on src/faq/code-faq.md
> +Longer Answer: Most of the use of the `unsafe` keyword is related to working with the scene tree as well as working with the Godot libraries. This is due to the lack of static analysis over the engin
That's a good point, I think you are right. When I look at the example, that's the same line of reasoning that I was going for, but I couldn't put it into words directly above.

I will update it.

2021-09-07 01:23 UTC, jacobsky commented on src/faq/code-faq.md
> +    // It is up to the programmer to ensure that this function call will not result in undefined behavior.
That's a much better point, I will add that.

2021-09-07 01:30 UTC, jacobsky commented on src/faq/code-faq.md
> +    Returns a resource from the filesystem that is loaded during script parsing. (emphasis mine)
Oops! I just copy pasted that from one of the questions directly. I'll add in the emphasis. :)

2021-09-07 01:31 UTC, jacobsky commented on src/faq/code-faq.md
> +```swift
I've used swift since it gives *some* syntax highlighting. It's only marginally more accurate than regular text though.
I'll switch it over to gdscript 👍 I didn't know that github supports it 😆

2021-09-07 01:35 UTC, jacobsky commented on src/faq/code-faq.md
> +    // It should also be possible to create an null `Ref<Node>` but
That's a good point. I'll go ahead and remove that.

2021-09-07 01:40 UTC, jacobsky commented on src/faq/configuration-faq.md
> +5. For each desired target, select a path to the location of the library created by cargo.
Those are all a few oversights. I'll go ahead and correct them.

2021-09-07 01:53 UTC, jacobsky commented on src/faq/configuration-faq.md
> +> If your tool classes inherit `EditorPlugin`, `EditorImportPlugin` or other extensions, it is required that you set `reloadable = false` in the gdnative library where the tool class is defined.
Maybe just `Important` would suffice? I was trying to add some information here to let users know that using `reloadable=true` for editor plugins and that it may also be useful if the editor plugin needs to use a NativeClass script to maintain multiple libraries. I'll give this a rewrite and see if I can make it make more sense.

2021-09-07 02:12 UTC, jacobsky commented on src/faq/configuration-faq.md
> +Yes. You can create as many libraries as you need for your project. Do be mindful that it is possible for name collision to occur when loading from multiple dynamic libraries. This can occur in the e
I'll add that in. It's definitely useful for certain use-cases, but I agree. We should probably indicate the "preferred" way of working with the library.

2021-09-07 02:12 UTC, jacobsky commented on src/faq/help-faq.md
> +# Help FAQ
I like it! I'll change it.

2021-09-07 02:13 UTC, jacobsky commented on src/faq/help-faq.md
> +- [NativeClass](https://docs.rs/gdnative/0.9.3/gdnative/derive.NativeClass.html) includes all the derive macro attributes that you can use to integrate your script class with godot.
Thank you for the feedback, I made all the changes.

2021-09-07 02:22 UTC, jacobsky commented on src/faq/multithreading-faq.md
> +Multi-threading with Servers would require that you manually create a threadpool that can hold the reference to the Server. Additional testing is required to ensure that this is an actual optimizatio
I spent quite a bit playing with this myself in my own project. 😆 I hope it helps someone else 😄

2021-09-07 02:28 UTC, jacobsky commented on src/faq/tooling-faq.md
> +##  What about performance? Is this binding speed up final Godot build?
I like it!

2021-09-07 02:28 UTC, jacobsky commented on src/faq/tooling-faq.md
> +Caveat: The above apply only to release builds with appropriate release settings. When comparing to debug builds in Rust are very, very slow.
That's a good point. I'll add that.

2021-09-07 02:29 UTC, jacobsky commented on src/faq/tooling-faq.md
> +Caveat 2: It is still possible to write rust code that has poor performance. You will still need to be mindful of the specific algorithms that you are choosing.
That's a great addition, I'll add that.

2021-09-07 02:29 UTC, jacobsky commented
@Bromeon Thank you for all the valuable insight. I've gone ahead and incorporated your changes. I appreciate the thorough look into the full FAQ. If you have any additional changes, please feel free to let me know.

2021-09-07 07:17 UTC, Bromeon commented on src/faq/configuration-faq.md
> +> If your tool classes inherit `EditorPlugin`, `EditorImportPlugin` or other extensions, it is required that you set `reloadable = false` in the gdnative library where the tool class is defined.
Wasn't about the word "considerations", rather the 2 sentences below.

I see; do you want to format them like regular bullet points (instead of `>`)?
The "Important considerations" itself should not be indented.

2021-09-07 12:34 UTC, jacobsky commented on src/faq/configuration-faq.md
> +> If your tool classes inherit `EditorPlugin`, `EditorImportPlugin` or other extensions, it is required that you set `reloadable = false` in the gdnative library where the tool class is defined.
I think that might make more sense. I'll fix the formatting and push a follow-up change.

2021-09-07 12:43 UTC, jacobsky commented
@Bromeon Alrighty. I think the most recent push should resolve the last of the changes. Please let me know if there's anything else that needs doing :)

2021-09-07 13:07 UTC, jacobsky commented
Also I just noticed, but I believe this resolves issue #23 and possibly #5

2021-09-07 13:59 UTC, Bromeon commented
It also overlaps somewhat with https://github.com/godot-rust/book/pull/24.
That would be 4-in-1, do you think we'll manage 5? 😬

2021-09-07 15:04 UTC, jacobsky commented
@Bromeon To ensure that we can close #5 I went ahead and added a section on profiling to "code-faq.md" at the bottom. I'm starting to think that I'll need to work on another PR to make some sub-sections for "code-faq" since it's getting pretty long and a little mixed up/hard to follow.

2021-09-08 07:12 UTC, Bromeon requested changes
I agree, this PR is already big enough, we can always add more and refine things in the future 🙂

2021-09-08 07:12 UTC, Bromeon commented on src/SUMMARY.md
> +  - [Community](./faq/community-faq.md)
The `-faq` suffix seems redundant to me here as `/faq` is already in the path. Is there a specific reason for this naming? We don't have `logging-recipe.md` either, for example.

2021-09-08 07:12 UTC, Bromeon commented on src/faq/code-faq.md
> +The problem is that unless the connected node's all connect with the `Object::CONNECT_DEFERRED` it will immediately (as if it were a callback) notify the nodes and they will attempt to borrow the dat
"node's" -> "nodes"

I would restructure the sentence a bit, to make it easier to understand:

> The problem is that, unless the nodes all connect with the `Object::CONNECT_DEFERRED` flag, they will be notified immediately and will attempt to borrow the data. This is the root cause of the `BorrowFailed` error.

2021-09-08 07:12 UTC, Bromeon commented on src/faq/code-faq.md
> +2. Make `data` in a `RefCell<LargeData>` if it should only be accessed from the same thread (such as with signals) or `Mutex<LargeData>` if you need thread-safety to be important. Then you can modify
maybe "Store `data`" instead of "Make"?

"to be important" can be omitted, I think.

Last sentence is incomplete, and I think it should be "`update_data()`".

2021-09-08 07:12 UTC, Bromeon commented on src/faq/code-faq.md
> +2. In godot-rust, rather than considering `&` and `&mut` as immutable and mutable, it may make more sense to consider it as "shared" and "unique". As the Rust bindings can't guarantee that access wil
Now that I read it again, point 2 and 1 are exactly the same. I think we can remove point 2 entirely, no?

2021-09-08 07:12 UTC, Bromeon commented on src/faq/code-faq.md
> +- C FFI: Any interactions that cross the C Foreign Function Interface will be unsafe by default as Rust cannot guarantee safety. While many functions may be safely reasoned about, there are still som
Good point! 👍🏼

2021-09-08 07:12 UTC, Bromeon commented on src/faq/code-faq.md
> +Here is a documented example with some of the unsafe usage that you will seem
Both incomplete 🙂

2021-09-08 07:12 UTC, Bromeon commented on src/faq/code-faq.md
> +Assuming that a method takes an argument `my_object` as a `Variant`
I think it's not clear what `my_object` is. Maybe `Object` is also not a typical example, because people usually deal with nodes.

Should we assume that the declaration looks something like this:
```rs
#[derive(NativeClass)]
#[inherit(Node2D)] // something specific, so it's clear when this type re-occurs in code
struct MyNode { ... } // instead of MyObject
```

We can also do the same thing with `Object` instead of `Node2D`, but then `self` (i.e. `AnotherNativeScript`) should not _also_ inherit `Object`.

2021-09-08 07:12 UTC, Bromeon commented on src/faq/code-faq.md
> +            .expect("Failed to cast my_object object to instance");
Mention that step 2 gives access to the Rust object (i.e. custom user data).

2021-09-08 07:12 UTC, Bromeon commented on src/faq/code-faq.md
> +While a similar case applies for [`ShaderMaterial`](https://docs.rs/gdnative/latest/gdnative/api/shader_material/struct.ShaderMaterial.html) in the case of shader material, to set the shader paramete
`SpatialMaterial` link broken, missing []

Can you add backticks around `albedo_texture` and `set_param`?

2021-09-08 07:12 UTC, Bromeon commented on src/faq/code-faq.md
> +- [`String`] and [`GodotString`](https://docs.rs/gdnative/latest/gdnative/core_types/struct.GodotString.html).
`String` could link to https://doc.rust-lang.org/std/string/struct.String.html

2021-09-08 07:12 UTC, Bromeon commented on src/faq/code-faq.md
> +- Godot classes such as `Node`, `Reference`, etc. which must be accessed via [`Ref<T>`](https://docs.rs/gdnative/latest/gdnative/struct.Ref.html) through Ref<T> (you can't pass them by value, because
remove "through Ref", we already have "via Ref"

2021-09-08 07:12 UTC, Bromeon commented on src/faq/code-faq.md
> +- The function belongs to a struct that derives `#[NativeClass]`
I would just write `NativeClass` -- `#[NativeClass]` never appears in code.

2021-09-08 07:12 UTC, Bromeon commented on src/faq/code-faq.md
> +As such, this method is _only_ useful for exported code and is subject
incomplete

2021-09-08 07:12 UTC, Bromeon commented on src/faq/tooling-faq.md
> +Long Answer: Rust and Godot are natively available for Windows, PC, Linux, Android and iOS export targets.
"Windows, PC" should just be "Windows", no?

2021-09-08 07:12 UTC, Bromeon commented on src/faq/tooling-faq.md
> +The official Godot documentation goes into more details with how this works from a Godot perspective. Please keep in mind that this does not necessarily extend to GDNative. [Console Support with Godo
Maybe the link can be embedded directly into the text instead of appended at the end. Press "quote comment" to get the formatting:

The official Godot documentation [goes into more details](https://docs.godotengine.org/en/stable/tutorials/platform/consoles.html) with how this works from a Godot perspective. Please keep in mind that this does not necessarily extend to GDNative.

2021-09-08 07:12 UTC, Bromeon commented on src/faq/tooling-faq.md
> +## How can I mke my debug builds more performant?
"make" typo

2021-09-08 07:16 UTC, jacobsky commented on src/SUMMARY.md
> +  - [Community](./faq/community-faq.md)
No specific reason, I just named it. I think you are right, we can go ahead and remove the faq from the name.

2021-09-08 07:18 UTC, jacobsky commented on src/faq/code-faq.md
> +The problem is that unless the connected node's all connect with the `Object::CONNECT_DEFERRED` it will immediately (as if it were a callback) notify the nodes and they will attempt to borrow the dat
Thank you for the change, I'll include it :)

2021-09-08 07:20 UTC, jacobsky commented on src/faq/code-faq.md
> +2. Make `data` in a `RefCell<LargeData>` if it should only be accessed from the same thread (such as with signals) or `Mutex<LargeData>` if you need thread-safety to be important. Then you can modify
I'll update it.

2021-09-08 07:23 UTC, jacobsky commented on src/faq/code-faq.md
> +2. In godot-rust, rather than considering `&` and `&mut` as immutable and mutable, it may make more sense to consider it as "shared" and "unique". As the Rust bindings can't guarantee that access wil
Yeah, that's a good point. I suppose unless we really needed to emphasize it, it would be better to go ahead and remove number 2.

2021-09-08 07:35 UTC, jacobsky commented on src/faq/code-faq.md
> +Here is a documented example with some of the unsafe usage that you will seem
I'll fix that up. Oops!

2021-09-08 07:43 UTC, jacobsky commented on src/faq/code-faq.md
> +Assuming that a method takes an argument `my_object` as a `Variant`
That's a much better example. I'll make the change

2021-09-08 07:45 UTC, jacobsky commented on src/faq/code-faq.md
> +- [`String`] and [`GodotString`](https://docs.rs/gdnative/latest/gdnative/core_types/struct.GodotString.html).
Ah! I forgot that!

2021-09-08 08:22 UTC, jacobsky commented on src/faq/code-faq.md
> +As such, this method is _only_ useful for exported code and is subject
😅 I'll finish that.

2021-09-08 08:25 UTC, jacobsky commented on src/faq/tooling-faq.md
> +## How can I mke my debug builds more performant?
😅

2021-09-09 11:40 UTC, Bromeon commented
Thanks a lot for this huge contribution! Will definitely help a lot of newcomers to navigate 🙂

2021-09-09 11:41 UTC, merged