Added a recipe for loading godot-external recipes.
godot-rust/gdnative-book pull request #34
Opened 2021-09-06 02:13 UTC by jacobsky

I added this recipe to help users that may need to include non-Godot resources for their rust-side configuration. Please let me know if there are any additional changes or tweaks that you would like me to make to this.

2021-09-06 07:26 UTC, Bromeon reviewed
Thanks, this is very helpful!

Maybe as a third option, we should mention files that are opened normally from Rust (via `std::fs`), and live outside the .pkg file? There could be a few things to consider regarding paths. I could imagine this for anything that also needs to be written (config, savegames, highscores etc.) -- what do you think?

2021-09-06 07:26 UTC, Bromeon commented on src/recipes/loading_external_resources.md
> +## Option 2 - Embedd the File in the PCK
"Embed" 🙂

2021-09-06 07:26 UTC, Bromeon commented on src/recipes/loading_external_resources.md
> +This can be accomplished by using the `gdnative::apis::File` module as follows.
`api`, not `apis`

2021-09-06 07:26 UTC, Bromeon commented on src/recipes/loading_external_resources.md
> +    // let line: PoolStringAray = file.get_csv_line(0);
This type is currently called [`StringArray`](https://docs.rs/gdnative/0.9.3/gdnative/core_types/type.StringArray.html) in godot-rust, I'm not very happy with the current naming though: https://github.com/godot-rust/godot-rust/issues/773

Same for `ByteArray` below.

2021-09-06 08:47 UTC, jacobsky commented on src/recipes/loading_external_resources.md
> +    // let line: PoolStringAray = file.get_csv_line(0);
Thanks for the correction!

2021-09-06 08:47 UTC, jacobsky commented on src/recipes/loading_external_resources.md
> +This can be accomplished by using the `gdnative::apis::File` module as follows.
Oops! I'll fix that.

2021-09-06 09:07 UTC, jacobsky commented
> Thanks, this is very helpful!

Glad to hear it.

> Maybe as a third option, we should mention files that are opened normally from Rust (via std::fs), and live outside the .pkg file? > There could be a few things to consider regarding paths. I could imagine this for anything that also needs to be written (config,savegames, highscores etc.) -- what do you think?

I think it would be useful to mention files that live outside the `.pck` file. It would be useful to -- at the very least -- confirm that it's mostly the same. The one problem that I've found with using the `std::fs::File` is that it's difficult to get the correct directories from Godot. My first attempt at doing this was to get the root directory, but it seems like Godot intentionally obfuscates that.

For now, I'll go ahead and include a mention of saving and loading from the "user://" with the `gdnative::api::File` since it is also likely something that users will be interested in noting.

If you have any idea on how to get the canonical paths from Godot, I'd be happy to add another option for using `std::fs::File`.

2021-09-06 10:36 UTC, Bromeon commented
Ah good, wasn't aware about the troubles with getting the root path. Feel free to also leave some TODOs in italics in the FAQ, that way we won't miss that some parts still need completing.

What do you think about Rust file I/O that disregards the Godot paths (`res://` and `user://`)? It's probably more an anti-pattern, no?

2021-09-06 14:26 UTC, jacobsky commented
> Ah good, wasn't aware about the troubles with getting the root path. Feel free to also leave some TODOs in italics in the FAQ, that way we won't miss that some parts still need completing.

Will do :)

> What do you think about Rust file I/O that disregards the Godot paths (`res://` and `user://`)? It's probably more an anti-pattern, no?

From my experimentation, I'd say using Rust I/O is probably less idiomatic for a Godot project. Since Godot makes a large number of assumptions about your project structure, I'd probably say that the general case would be to use `ResourceLoader` or `File` first and only if those are not an option try to work with Rust I/O,

That being said, I doubt there's any reason that you couldn't, but it would take some additional effort to ensure that you can always find "res://" or "user://" and that you can read from the .PCK file. While .PCK is a fancy zip file, it still requires grabbing another package to read through the ZIP file (or is that supported natively in rust?) and then you'd need to do the extra leg work. It's probably just easier to use the `File` API, :D

2021-09-10 15:51 UTC, jacobsky commented
Fixed up a merge conflict with SUMMARY.md between this and the previous commit.

2021-09-12 07:25 UTC, Bromeon requested changes
Thanks for the additions!

2021-09-12 07:25 UTC, Bromeon commented on src/recipes/loading_external_resources.md
> +To embedd the file directly into the binary you can use
"embed"

and I would generally close sentences which refer to a following section with a colon ":".

2021-09-12 07:25 UTC, Bromeon commented on src/recipes/loading_external_resources.md
> +```
Indentation is strange here -- can you un-indent the `const` and comment?
Also, an empty line between the constant and the function definition would make things a bit clearer.

2021-09-12 07:25 UTC, Bromeon commented on src/recipes/loading_external_resources.md
> +    file.open(filepath, File::READ).expect(&format!("{} must exist", &filepath));
`filepath` is `&str`, so no need to take a reference to it.

2021-09-12 07:25 UTC, Bromeon commented on src/recipes/loading_external_resources.md
> +    let data: StringArray = file.get_as_text();
`get_as_text()` returns `GodotString`, not `StringArray`.

2021-09-12 07:25 UTC, Bromeon commented on src/recipes/loading_external_resources.md
> +For example: such as if you wish to hard-code certain features (e.g. cheat codes, developer consoles, default user configuration) and organize them as a file rather than a build flag.
"such as" and "e.g." are redundant when you already have "For example:"

2021-09-12 07:25 UTC, Bromeon commented on src/recipes/loading_external_resources.md
> +    // let line: PoolStringAray = file.get_csv_line(0);
You resolved it, but it seems not changed, or am I missing something?

2021-09-12 07:25 UTC, Bromeon commented on src/recipes/loading_external_resources.md
> +See the [File Class Documentation](https://docs.godotengine.org/en/stable/classes/class_file.html) for every function that you use for loading the resources.
Should we link to https://docs.rs/gdnative/latest/gdnative/api/struct.File.html instead?
There's still a link there to the Godot doc, but I think it would be more helpful to know the involved Rust types.

Also, maybe write "`File` class documentation" 🙂

2021-09-12 07:25 UTC, Bromeon commented on src/recipes/loading_external_resources.md
> +    file.store_string(data.to_owned());
[`File::store_string()`](https://docs.rs/gdnative/0.9.3/gdnative/api/struct.File.html#method.store_string) takes a parameter `string: impl Into<GodotString>`. So it can accept any `T` for which `From<T>` is implemented for `GodotString`.

[There is](https://docs.rs/gdnative/latest/gdnative/core_types/struct.GodotString.html#impl-From<S>) a
```rust
impl<S> From<S> for GodotString
   where S : AsRef<str>
```
so we should be able to pass `data` directly, no? Would be nice to avoid the intermediate copy through `String`.

2021-09-12 07:25 UTC, Bromeon commented on src/recipes/loading_external_resources.md
> +    let data: StringArray = file.get_as_text();
same here: `GodotString`

2021-09-12 07:25 UTC, Bromeon commented on src/recipes/loading_external_resources.md
> +For test configurations, it will be necessary to use `std::fs:File` to load the resources for testing. This can be accomplished by creating separate code paths or functions `#[cfg(test)]` and `#[cfg(
It's not entirely clear to me why this is necessary -- do you mean that one should have a separate, Rust-only configuration for tests?

2021-09-12 07:29 UTC, Bromeon commented on src/SUMMARY.md
> +    - [Loading External Dependencies](./recipes/loading_external_resources.md)
I would keep the name here and the title in sync. I think "Resource files" fits better than "Dependencies".

Capitalization-wise, I would only capitalize the first word and symbol names; i.e. here I'd write "Loading external resource files" or "Loading external resources" (and 1:1 for the title in the .md file).

2021-09-12 09:14 UTC, jacobsky commented on src/recipes/loading_external_resources.md
> +    // let line: PoolStringAray = file.get_csv_line(0);
I'll make sure that this gets fixed. (I may have forgotten to push the changes 😨)

2021-09-12 09:21 UTC, jacobsky commented on src/recipes/loading_external_resources.md
> +See the [File Class Documentation](https://docs.godotengine.org/en/stable/classes/class_file.html) for every function that you use for loading the resources.
That's a good point! I'll make the changes.

2021-09-12 09:22 UTC, jacobsky commented on src/recipes/loading_external_resources.md
> +    file.store_string(data.to_owned());
That's a good point. I just verified it in my other code and I do not use `to_owned()` there.

2021-09-12 09:24 UTC, jacobsky commented on src/recipes/loading_external_resources.md
> +For test configurations, it will be necessary to use `std::fs:File` to load the resources for testing. This can be accomplished by creating separate code paths or functions `#[cfg(test)]` and `#[cfg(
This section is for unit/integration testing from rust without loading Godot. As `gdnative::api::File` requires that Godot be running to use it, it's necessary for any code that is going to be loaded to have a test configuration in order to load it. I'm not sure if this section is entirely necessary, but I thought it would be useful to include. If you have any suggestions, I would be happy to make modifications.

2021-09-12 09:55 UTC, Bromeon commented on src/recipes/loading_external_resources.md
> +For test configurations, it will be necessary to use `std::fs:File` to load the resources for testing. This can be accomplished by creating separate code paths or functions `#[cfg(test)]` and `#[cfg(
I didn't question the necessity of the section, but literally the sentence "it will be necessary to use `std::fs:File`" 😉 

Definitely keep the section! I think adding what you mentioned would clarify a lot for the reader:
> This section is for unit testing from Rust without loading Godot. As `gdnative::api::File` requires that Godot be running to use it, it's necessary for any code that is going to be loaded to have a test configuration in order to load it.

2021-09-12 13:52 UTC, jacobsky commented on src/recipes/loading_external_resources.md
> +For test configurations, it will be necessary to use `std::fs:File` to load the resources for testing. This can be accomplished by creating separate code paths or functions `#[cfg(test)]` and `#[cfg(
Thanks for the input. I've made the changes.

2021-09-12 13:55 UTC, jacobsky commented
@Bromeon I made the requested changes.

2021-09-12 14:46 UTC, Bromeon commented on src/recipes/loading_external_resources.md
> +    // let bytes: PoolByteArray = file.get_bytes(file_len);
`StringArray/ByteArray` 🙂

2021-09-12 14:46 UTC, Bromeon commented on src/recipes/loading_external_resources.md
> +For more information on the paths, please refer to the [File System Tutorial](https://docs.godotengine.org/en/3.0/getting_started/step_by_step/filesystem.html#resource-path) for more inforamtion.
"inforamtion" typo

2021-09-12 14:46 UTC, Bromeon commented on src/recipes/loading_external_resources.md
> +This section is for unit testing from Rust without loading Godot. As `gdnative::api::File` requires that Godot be running to use it, it's necessary for any code that is going to be loaded to have a t
> As `gdnative::api::File` requires that Godot be running to use it, it's necessary for any code that is going to be loaded to have a test configuration in order to load it.

Sounds a bit like circular reasoning; I would probably write something like:

As `gdnative::api::File` requires that Godot be running, a Rust-only unit test for loading needs to be implemented without it.

2021-09-12 14:46 UTC, Bromeon commented on src/recipes/loading_external_resources.md
> +// To have global immutible access to the file.
"immutable"

2021-09-12 15:11 UTC, jacobsky commented on src/recipes/loading_external_resources.md
> +    // let bytes: PoolByteArray = file.get_bytes(file_len);
Ah, right they are named differently in gdnative. Ooops!

2021-09-12 15:13 UTC, jacobsky commented
@Bromeon I just finished the last round of changes. Please let me know if there are any additional. If not, I'll go ahead and squash the commits for merging.

2021-09-12 18:12 UTC, merged