Game architecture and organization
godot-rust/gdnative-book pull request #36
Opened 2021-09-20 13:45 UTC by Bromeon

2021-09-21 04:50 UTC, jacobsky requested changes
Thank you for the hard work on this PR. This is a great article and I think the images help tremendously with understanding the whole thing.

Most of my comments are on the nitpicky side, feel free to disregard any that you disagree with substantially, I just wanted to make sure to add all of my thoughts.

Great section!

2021-09-21 04:50 UTC, jacobsky commented on src/gdnative-overview/architecture.md
> +_This chapters assumes that you are developing a game with Godot and Rust, however many of the points apply to other projects like simulations or visualizations._
As this is two independent clauses you should use a semi-color like the following

... with Godot and Rust; however, many of the points ...

2021-09-21 04:50 UTC, jacobsky commented on src/gdnative-overview/architecture.md
> +With respect to architecture, godot-rust offers a lot of freedom and does not force a certain model upon you. How much you want to develop in GDScript and how much in Rust, is entirely up to you. The
This is a great section. Small nitpicks

"With respect to architecture, " might be more readable as "Regarding architecture, godot-rust offers a lot of freedom and does not force you into certain patterns or architectures."


I would also put "Each language has their own strengths and weaknesses:" on a separate line to emphasize that were doing a proper comparison next.

2021-09-21 04:50 UTC, jacobsky commented on src/gdnative-overview/architecture.md
> +To give you some guide, this chapter highlights three typical patterns. That does not mean you have to adhere to any of them; sometimes hybrid solutions or entirely different designs are worth consid
I like that this area also pointed out everything is intended to highlight some typical patterns while also mentioning that there is room for both.

I made a few tweaks for readability. I think the two most important points were to include that "entirely different designs are also worth considering" so that it feels a little more inclusive and to avoid using acronyms (I wasn't familiar with what "w.r.t." meant initially, so writing out the full word may be more immediately obvious.

A sample for my thoughts is below.

"As a starting point, this chapter highlights three common patterns that have been successfully used with godot-rust. This does not mean you must adhere to any of them; depending upon your system hybrid solutions or entirely different designs are also worth considering. The three patterns are listed with respect to complexity and scalability."

2021-09-21 04:50 UTC, jacobsky commented on src/gdnative-overview/architecture.md
> +Now, you figure out there is a feature which you don't want to implement in GDScript. Maybe because of performance, or maybe because you want to pull in functionality from the Rust ecosystem, for exa
This is a little wordy, so how about the following?

During development, you encounter a feature which you wish to develop in Rust while making this accessible to GDScript. Reasons may include:
- The code is performance critical and GDScript was not fast enough.
- There is a Rust based library that you wish to use, for example, pathfinding, AI, Physics
- You have a segment of your code with high complexity that is difficult to manage in GDScript

2021-09-21 04:50 UTC, jacobsky commented on src/gdnative-overview/architecture.md
> +* As most of the game logic is in GDScript, you cannot benefit from Rust's features, type safety and refactoring capabilities.
It might be more natural to say "and you receive limited benefits from Rust's features"

2021-09-21 04:50 UTC, jacobsky commented on src/gdnative-overview/architecture.md
> +When developing a game in Godot alone, the engine encourages a certain pattern: each game entity is represented by a scene node, and the logic for each node is implemented in a GDScript file. With go
I feel like the following may be a little more clear.

"Godot Engine encourages a certain pattern: "

"You can follow the same architecture with godot-rust, the only difference is that the scripts are implemented in Rust."

2021-09-21 04:50 UTC, jacobsky commented on src/gdnative-overview/architecture.md
> +3. **Output:** These results are passed back to Godot and take effect in the scene (node positions, animations, sound effects, ...)
needs a fullstop at the end.

2021-09-21 04:50 UTC, jacobsky commented on src/gdnative-overview/architecture.md
> +   * Rust-only headless server
Next 3 are missing the fullstop at the end. That's probably fine so long as it's consistent within the same bulleted list (imo), I just wanted to point it out in case it was a miss.

2021-09-21 04:50 UTC, jacobsky commented on src/gdnative-overview/architecture.md
> +This might be the most scalable workflow, but it also needs a lot of discipline, and you have to do certain things manually that the other options give you for free.
This workflow can be the most scalable and "Rusty" workflow, but this also requires a lot of discipline. In addition, you will lose certain functionality in the editor, such as the Node tree, without additional work.

2021-09-21 04:50 UTC, jacobsky commented on src/gdnative-overview/architecture.md
> +* You have little architectural freedom and need to orient your entities to Godot's scene tree model.
Perhaps something like: "You are generally constrained to Godot's SceneTree model".

2021-09-21 04:50 UTC, jacobsky commented on src/gdnative-overview/architecture.md
> +* godot-rust is needed throughout your entire code base, tightly coupling your game logic to Godot. This means that testing and isolating functionality will be harder, and you may need to adjust larg
This is really good, but it might flow better with something like the following:

"As godot-rust is used throughout your entire codebase, this will tightly couple your game logic to Godot. Testing and isolating functionality can be harder and you are more subject to Godot's version changes."

2021-09-21 07:47 UTC, Bromeon commented on src/gdnative-overview/architecture.md
> +With respect to architecture, godot-rust offers a lot of freedom and does not force a certain model upon you. How much you want to develop in GDScript and how much in Rust, is entirely up to you. The
Thanks!
I would maybe write:

"Regarding architecture, godot-rust offers a lot of freedom and does not force you into certain patterns ~or architectures~."

As we have the repetition otherwise.

2021-09-21 07:52 UTC, Bromeon commented on src/gdnative-overview/architecture.md
> +To give you some guide, this chapter highlights three typical patterns. That does not mean you have to adhere to any of them; sometimes hybrid solutions or entirely different designs are worth consid
Great improvement, I'll adopt this!
Regarding "depending upon your system", would it make sense to use "needs" or "requirements" instead of "system"?

And "The three patterns are listed with respect to complexity and scalability."
Does this imply ascending order?

2021-09-21 08:00 UTC, Bromeon commented on src/gdnative-overview/architecture.md
> +Now, you figure out there is a feature which you don't want to implement in GDScript. Maybe because of performance, or maybe because you want to pull in functionality from the Rust ecosystem, for exa
Good points, I'll replace it! Also I like the 3rd bullet point 🙂

I would do minor changes in wording/punctuation:
* "while making ~this~ **it** accessible to GDScript."
* "Rust-based"
* "for example pathfinding, AI or physics"

Makes sense?

2021-09-21 08:04 UTC, Bromeon commented on src/gdnative-overview/architecture.md
> +* As most of the game logic is in GDScript, you cannot benefit from Rust's features, type safety and refactoring capabilities.
Is "to receive benefit from" more natural than "to benefit from"?
It sounds to me like literally obtaining benefits (e.g. financial), while "to benefit from" sounds like having an advantage (i.e. what we want to say). But I'm not a native speaker...

2021-09-21 08:05 UTC, Bromeon commented on src/gdnative-overview/architecture.md
> +   * Rust-only headless server
Here it's just keywords, not full sentences, so I think it's OK.
I agree though that we should try to be consistent within one bullet list.

2021-09-21 08:14 UTC, Bromeon commented on src/gdnative-overview/architecture.md
> +This might be the most scalable workflow, but it also needs a lot of discipline, and you have to do certain things manually that the other options give you for free.
Here I didn't want to explicitly mention drawbacks, as they are part of the bullet list already, but I wanted to make clear that the other approaches give some things for free which one has to do by hand in this case.

Maybe:

> This can be the most scalable and "Rusty" workflow, but it also requires a lot of discipline. You will need to handcraft some glue code that the other workflows offer for free.

2021-09-21 08:17 UTC, Bromeon commented on src/gdnative-overview/architecture.md
> +* godot-rust is needed throughout your entire code base, tightly coupling your game logic to Godot. This means that testing and isolating functionality will be harder, and you may need to adjust larg
Great wording! Also added "Godot's **and godot-rust's** version changes" 👍🏼

2021-09-21 08:24 UTC, Bromeon commented
Thanks a lot for the feedback! Pushed an amended version as a separate commit.

2021-09-21 23:55 UTC, jacobsky commented on src/gdnative-overview/architecture.md
> +With respect to architecture, godot-rust offers a lot of freedom and does not force a certain model upon you. How much you want to develop in GDScript and how much in Rust, is entirely up to you. The
Yeah that's perfect!

2021-09-21 23:59 UTC, jacobsky commented on src/gdnative-overview/architecture.md
> +To give you some guide, this chapter highlights three typical patterns. That does not mean you have to adhere to any of them; sometimes hybrid solutions or entirely different designs are worth consid
>  Regarding "depending upon your system", would it make sense to use "needs" or "requirements" instead of "system"?
Yes, "depending upon your needs" or "depending upon your requirements" both flow a lot better.

> And "The three patterns are listed with respect to complexity and scalability."
> Does this imply ascending order?

After thinking about it, while it does imply ordering it doesn't necessary imply which kind of ordering. So doing "The three patterns are listed in ascending order with respect to complexity and scalability" is probably the most clear.

2021-09-21 23:59 UTC, jacobsky commented on src/gdnative-overview/architecture.md
> +Now, you figure out there is a feature which you don't want to implement in GDScript. Maybe because of performance, or maybe because you want to pull in functionality from the Rust ecosystem, for exa
Sounds perfect :)

2021-09-22 00:01 UTC, jacobsky commented on src/gdnative-overview/architecture.md
> +This might be the most scalable workflow, but it also needs a lot of discipline, and you have to do certain things manually that the other options give you for free.
That makes a lot of sense. I think your second version perfectly and succinctly describes that additional work required.

2021-09-22 00:18 UTC, jacobsky commented on src/gdnative-overview/architecture.md
> +* As most of the game logic is in GDScript, you cannot benefit from Rust's features, type safety and refactoring capabilities.
I think both are alright. I think "you will also be unable to receive many benefits of Rust's features" is also perfectly valid.

On second though, I think that you can probably keep it the way it is as well. I might have been a bit on the pedantic side because you will _technically_ gain some benefits from Rust (scripts written in Rust get those benefits), but the project as a whole will probably not.

I think we should mention the project in this setence.

"As most of the game logic is in GDScript, your project will not benefit from Rust's features, type safety and refactoring capabilities.

2021-09-22 00:19 UTC, jacobsky requested changes
Thank you for the second round of changes! I think this is pretty close to perfect. I added some comments on the previously unresolved points.

2021-09-22 07:58 UTC, Bromeon commented
Adjusted the discussed point. If the rest is good, I'll squash and merge.

2021-09-22 08:02 UTC, jacobsky approved these changes
Looks good to me! Thank you for the hard work :)

2021-09-28 19:08 UTC, merged