Add info about property attribute options
godot-rust/gdnative-book pull request #40
Opened 2021-10-25 16:44 UTC by mivort

This PR expands article about property export with examples for default value setting, creation of no-editor properties and value access/modification hooks.

It might come in handy for people migrating from GDScript.

2021-10-25 19:00 UTC, Bromeon requested changes
Thank you for the addition!

There's also [some documentation](https://godot-rust.github.io/docs/gdnative/derive/derive.NativeClass.html#property) in the API already, but I don't think it hurts to have larger examples in the book.

Added some comments.

2021-10-25 19:00 UTC, Bromeon commented on src/rust-binding/properties.md
> +# }
There are too many `#` line prefixes (this is Markdown, not Rustdoc). Also below.

2021-10-25 19:00 UTC, Bromeon commented on src/rust-binding/properties.md
> +    fn before_get(&self, owner: TRef<Node>) {
Should be `_owner` (also below).

2021-10-25 19:00 UTC, Bromeon commented on src/rust-binding/properties.md
> +You can add hooks to call methods before and after property value was retrieved or changed.
Maybe add this for clarification:

> Note that unlike [GDScript's `setget` keyword](https://docs.godotengine.org/en/3.3/getting_started/scripting/gdscript/gdscript_basics.html?#setters-getters), this does _not_ register a custom setter or getter. Instead, it registers a callback which is invoked _before or after_ the set/get occurs, and lacks both parameter and return value.

2021-10-25 19:31 UTC, mivort commented on src/rust-binding/properties.md
> +You can add hooks to call methods before and after property value was retrieved or changed.
That's a very nice note indeed! Added.

2021-10-25 19:32 UTC, mivort commented on src/rust-binding/properties.md
> +    fn before_get(&self, owner: TRef<Node>) {
Done, added `_` prefixes.

2021-10-25 19:34 UTC, mivort commented on src/rust-binding/properties.md
> +# }
I've added these as hidden lines to make example 'a bit' more complete, but since it still doesn't compile with the Run button, I suppose there's no need for that... removed it.

2021-10-25 20:54 UTC, Bromeon approved these changes
Looks good! If you could [combine the commits into a single one](https://stackoverflow.com/q/5189560), it should be ready to merge 🙂

2021-10-25 21:03 UTC, mivort commented
Done, squashed all appends into single commit :)

2021-10-26 00:06 UTC, jacobsky approved these changes
Thank you for the additional examples! This is a great addition to the properties section (which I always felt was a bit lacking).

After the latest changes it looks good to me.

2021-10-26 05:52 UTC, merged