ClassBuilder, ToVariant/FromVariant and Export explanations.
godot-rust/gdnative-book pull request #51
Opened 2021-10-30 04:15 UTC by jacobsky

To resolve Issue #38 I have added some entries in `rust-bindings/properties.md`
In addition, I added a section that can better explain the `ToVariant`, `FromVariant` and `Export` traits as these are going to end up being really common issues for folks that work heavily with the Godot Editor.

I am opening this as a draft for some initial feedback on the ideas not necessarily the typos, if I have any major misunderstandings in my explanations please let me know so I can update it. Please don't worry about typos for the time being as I plan to go over and edit this again.

2021-11-14 11:18 UTC, jacobsky commented
I've gone over and fixed up this PR.

 @Bromeon If you have any feedback or nitpicks, please let me know otherwise I'll go ahead and squash/merge it.

2021-11-14 13:01 UTC, Bromeon requested changes
Thanks a lot for the write-up!
I added some comments.

2021-11-14 13:01 UTC, Bromeon commented on src/rust-binding/properties.md
> +## Manual Property Registration
Upper/lowercase 😬 
```
Manual property registration
```

2021-11-14 13:01 UTC, Bromeon commented on src/rust-binding/properties.md
> +This is often the case where custom hint behaivor is desired for primitive types, such as an Integer value including an `IntEnum` hint.
"behaivor" typo

2021-11-14 13:01 UTC, Bromeon commented on src/rust-binding/properties.md
> +        // Register the number as an Enum
Maybe empty line before each of these, to separate the different ways of calling the builder API?

2021-11-14 13:01 UTC, Bromeon commented on src/rust-binding/to-variant-from-variant-export.md
> +As seen in [the previous section](./properties.md), the `#[property]` attribute of the [NativeClass] procedural macro is a powerful tool for to automatically configuring properties with your Godot.
`[NativeClass]` should probably use backticks instead of brackets

Also, "powerful tool **_to automatically configure_** properties"

And "with your Godot" why is it mine? 🙂 
I think the "your" can be omitted.

2021-11-14 13:01 UTC, Bromeon commented on src/rust-binding/to-variant-from-variant-export.md
> +The ToVariant and FromVariant are conversion traits that allow Rust types to be converted between these types. All properties must implement both ToVariant and FromVariant while exported methods requ
Some missing backticks around From/ToVariant

2021-11-14 13:01 UTC, Bromeon commented on src/rust-binding/to-variant-from-variant-export.md
> +For many datatypes, it is possible to use the derive macros such as in the following example,
Probably you meant colon instead of comma?

2021-11-14 13:01 UTC, Bromeon commented on src/rust-binding/to-variant-from-variant-export.md
> +// Note: This struct does not implement `export` and cannot be used a property, see the following section for more information.
> does not implement `Export` _(uppercase)_ and cannot be used **_as_** a property, ...

2021-11-14 13:01 UTC, Bromeon commented on src/rust-binding/to-variant-from-variant-export.md
> +    // This type should normally be one of the types defined in [gdnative::nativescript::hint](https://docs.rs/gdnative/0.9.3/gdnative/nativescript/init/property/hint/index.html).
This link will soon be outdated, but it's a bit tricky.
Maybe leave it for 0.9.3 now, and we go through the book once we release 0.10.

2021-11-14 13:01 UTC, Bromeon commented on src/rust-binding/to-variant-from-variant-export.md
> +## Case Study: Exporting Rust enums to Godot and Back.
> ...and back

(lowercase, no full stop)

Also, less important, but if I'm not mistaken, English uses lowercase after colons, so it would be
> Case **_study: exporting_** Rust enums to Godot and back

2021-11-14 13:01 UTC, Bromeon commented on src/rust-binding/to-variant-from-variant-export.md
> +Will convert to a the following dictionary
excess "a", no colon

2021-11-14 13:01 UTC, Bromeon commented on src/rust-binding/to-variant-from-variant-export.md
> +    C { inner: String}
Maybe space before `}`, also below in GDScript code?

2021-11-14 13:01 UTC, Bromeon commented on src/rust-binding/to-variant-from-variant-export.md
> +By default, Rust enums are converted to a Dictionary representation with keys corresponding to each enum variant where the Enum Value corresponds to a Dictionary that contains the key-value pairs tha
This sentence is a bit hard to understand without commas. Maybe something like:

> By default, Rust enums are converted to a Dictionary representation. Its keys correspond to the name of the enum variants, while the values correspond to a Dictionary with fields as key-value pairs.

2021-11-14 13:01 UTC, Bromeon commented on src/rust-binding/to-variant-from-variant-export.md
> +This defines a simple enum where each enum value refers to an integer value
Comma before "where", fullstop at end

2021-11-14 13:01 UTC, Bromeon commented on src/rust-binding/to-variant-from-variant-export.md
> +If you were to try to add this to a NativeClass as a follows property you will receive errors similar to the following:
"as a follows property"?
What do you mean?

2021-11-14 13:01 UTC, Bromeon commented on src/rust-binding/to-variant-from-variant-export.md
> +After implementing export, you would also receive the following error:
If you mean the trait, should be `Export` with back ticks.
If you mean exporting in general, it's fine like this.

2021-11-14 13:01 UTC, Bromeon commented on src/rust-binding/to-variant-from-variant-export.md
> +            MyIntEnum::C => { Variant::from_i64(2) },
Since we're about to remove these (see https://github.com/godot-rust/godot-rust/issues/774 and Discord discussion), maybe write `0.to_variant()` instead? If you do, don't forget to `use gdnative::core_types::ToVariant;`.

2021-11-18 12:38 UTC, jacobsky commented on src/rust-binding/to-variant-from-variant-export.md
> +As seen in [the previous section](./properties.md), the `#[property]` attribute of the [NativeClass] procedural macro is a powerful tool for to automatically configuring properties with your Godot.
Thanks for the catch. I forgot to add the link to the docs for the `NativeClass` docs, so I will put it in backticks with the link like [`NativeClass`](https://docs.rs/gdnative/latest/gdnative/derive.NativeClass.html)

2021-11-18 12:42 UTC, jacobsky commented on src/rust-binding/to-variant-from-variant-export.md
> +    // This type should normally be one of the types defined in [gdnative::nativescript::hint](https://docs.rs/gdnative/0.9.3/gdnative/nativescript/init/property/hint/index.html).
That's a good point, I almost forgot about the whole module refactor, but I think it would be best to leave the link hardcoded. I can make a pass at checking that all of the links go to valid documentation after 0.10 is released.

2021-11-18 12:43 UTC, jacobsky commented on src/rust-binding/to-variant-from-variant-export.md
> +## Case Study: Exporting Rust enums to Godot and Back.
Good catch. I really need to stop my habit of considering headers titles, since they aren't actually titles :rofl:

2021-11-18 12:48 UTC, jacobsky commented on src/rust-binding/to-variant-from-variant-export.md
> +If you were to try to add this to a NativeClass as a follows property you will receive errors similar to the following:
Ah, this one was confusing. I fixed it up to be:
> This code defines the enum `MyIntEnum` where each enum value refers to an integer value.
> Without implementing the `FromVariant` and `Export` traits, attempting to export `MyIntEnum` as a property of `MyNode` will result in the following error:

2021-11-18 12:51 UTC, jacobsky commented on src/rust-binding/to-variant-from-variant-export.md
> +After implementing export, you would also receive the following error:
I meant the trait. Thanks for the catch!

2021-11-18 12:51 UTC, jacobsky commented on src/rust-binding/to-variant-from-variant-export.md
> +            MyIntEnum::C => { Variant::from_i64(2) },
Good catch!

2021-11-18 12:52 UTC, jacobsky commented
I added the fixes as requested. Let me know if there's anything else that you'd like to see changed :)

2021-11-24 18:40 UTC, Bromeon commented
Should be good, thanks! 🙂

2021-11-24 23:44 UTC, jacobsky commented
Thank you for the reviews! I'll go ahead and squash/merge the changes :)

2021-11-24 23:44 UTC, merged