Added faq entry on runtime polymorphism
godot-rust/gdnative-book pull request #55
Opened 2021-11-03 18:43 UTC by bluenote10

I'll give #54 a shot, feel free to adjust as needed ;)

I wasn't sure if this FAQ entry is the right place to explain `Deref` with its limitation, so I kept it at the bare minimum for now.

2021-11-04 03:26 UTC, jacobsky requested changes
Thank you for the PR! I greatly appreciate you bringing our attention to this subject in #54 

Overall this entry looks good, I just have two minor nitpicks related to making the phrasing a little more consistent with the rest of the FAQ.

2021-11-04 03:26 UTC, jacobsky commented on src/faq/code.md
> +## How to implement function arguments that accept any Godot subclass (runtime polymorphism)?
In this case it may be more consistent to change the question to "How do I..."? as that is consistent with other questions like "How do I keep a reference of Node?", etc.

2021-11-04 03:26 UTC, jacobsky commented on src/faq/code.md
> +Let's assume you want to implement a helper function that should accept any kind of [`Container`](https://docs.godotengine.org/en/stable/classes/class_control.html#class-control). This can be solved
This paragraph can probably be more clear if we split it into two sections:
1. The more generic answer like: "Access to the `SubClass` of a `TRef<T>` may be accessed via the `upcast` method.
2. An example:; "For example: if you wanted to implement a helper function..."

2021-11-04 09:26 UTC, Bromeon reviewed
Thanks a lot for the PR! Added small comments.

2021-11-04 09:26 UTC, Bromeon commented on src/faq/code.md
> +}
Could you run the code through rustfmt?
Should have 4 space indentation.

Same for the other snippet.

2021-11-04 09:26 UTC, Bromeon commented on src/faq/code.md
> +	let container = container.upcast();
Maybe annotate the type here explicitly?
That helps people understand what exactly `upcast()` does.

2021-11-04 18:50 UTC, bluenote10 commented on src/faq/code.md
> +}
I'm a formatting pedantic, how could that have happened to me :joy: (of course: a space vs tabs thing...)

2021-11-04 18:51 UTC, bluenote10 commented
Thanks for the suggestions, fully agreeing to everything, I hope I've fixed it all now.

2021-11-05 01:02 UTC, jacobsky approved these changes
Looks good to me! If you can just squash the commits, we can go ahead and merge it :)

2021-11-05 07:58 UTC, bluenote10 commented
Feel free to use the auto-squash, I don't care about the credits ;)

2021-11-05 10:08 UTC, merged