Add HTML5 export guide
godot-rust/gdnative-book pull request #71
Opened 2022-06-25 18:13 UTC by derivator

@Bromeon as discussed in [#647](https://github.com/godot-rust/godot-rust/issues/647) this should cover most of the current problems with HTML5 exports.

2022-06-26 14:03 UTC, jacobsky requested changes
Thank you so much for the PR! This is a great guide that helps better define how godot-rust supports HTML5 exports.

I have included some minor nitpicks on structure. I will also give this process a go to test this from my end.

@Bromeon feel free to let me know if you have any additional thoughts or questions on this addition

2022-06-26 14:03 UTC, jacobsky commented on src/exporting/html5.md
> +## General considerations
Since this export process doesn't have a trivial set up, I think this section can be called "Tooling Requirements", "Setup Requirements"  or something like that. This would make it more obvious to users that there are very specific requirements for this export process.

2022-06-26 14:03 UTC, jacobsky commented on src/exporting/html5.md
> +**Disclaimer**: _Currently, the following steps are only tested and confirmed to work on Linux._
It might be worth making this disclaimer into it's own section where we can include all of the additional version requirements. In the future, more folks may be able to test this and confirm working versions so having a section could be useful for new users.

2022-06-26 14:03 UTC, jacobsky commented on src/exporting/html5.md
> +### Getting Emscripten
Minor nitpick, "Installing and configuring Emscripten" might be a more appropriate section title.

2022-06-26 14:03 UTC, jacobsky commented on src/exporting/html5.md
> +### Building Godot
Does this require building Godot from source? or only the export template? If the latter, can we change the title to "Building Godot export template"

2022-06-26 14:03 UTC, jacobsky commented on src/exporting/html5.md
> +Set the newly built export template as a custom template in Godot and be sure to set the export type as GDNative. When exporting, uncheck "Export With Debug".
I'm assuming that the export template requires installing from a file as per: https://docs.godotengine.org/en/stable/tutorials/export/exporting_basics.html#export-templates

Is that correct? If so, can I ask for you to add the above link for completeness?

2022-06-26 15:50 UTC, derivator commented on src/exporting/html5.md
> +### Building Godot
As far as I can tell an export template is just a pre-built version of Godot, so these are the same thing. We are compiling the engine from source to wasm.

2022-06-26 15:55 UTC, derivator commented on src/exporting/html5.md
> +Set the newly built export template as a custom template in Godot and be sure to set the export type as GDNative. When exporting, uncheck "Export With Debug".
This is what I'm referring to: 
![image](https://user-images.githubusercontent.com/2171264/175822720-bcd2f1ff-0a1d-4495-9f9c-892d42e9bdcd.png)

We could link that image?

2022-06-26 16:04 UTC, derivator commented on src/exporting/html5.md
> +**Disclaimer**: _Currently, the following steps are only tested and confirmed to work on Linux._
I expect this whole section to become outdated very rapidly. What I said under "General Considerations" (matching emscripten versions) is fairly general, but building Godot will probably not be necessary with 3.6, and rust compiler flags could change any second now.

2022-06-26 16:57 UTC, Bromeon reviewed
This is an awesome addition, thank you very much! ❤️ 

Good that you highlighted that some of the guide might be obsolete soon. I think it's good to start somewhere, and update when needed. Hopefully, a smaller scale in updating also motivates more people to contribute 🙂

2022-06-26 16:57 UTC, Bromeon commented on src/exporting/html5.md
> +Set the newly built export template as a custom template in Godot and be sure to set the export type as GDNative. When exporting, uncheck "Export With Debug".
Sounds good to me!

2022-06-26 16:57 UTC, Bromeon commented on src/exporting/html5.md
> +In your project's `config.toml`, add the following:
This refers to the godot-rust crate which is compiled as a `cdylib`? If yes, maybe quickly mention that to resolve ambiguities 🙂

2022-06-26 16:57 UTC, Bromeon commented on src/exporting/html5.md
> +### Building Godot
Since you built Godot from source, did you use `gdnative` with the `custom-godot` Cargo feature?

2022-06-26 20:06 UTC, derivator commented
@Bromeon I don't use `custom-godot`, should I? I'm just rebuilding 3.4.4 with a newer Emscripten, but it's still 3.4.4

2022-06-26 20:36 UTC, Bromeon commented
@derivator You should only need `custom-godot` if the generated API JSON would differ from the one shipped in the godot-rust repo. This is usually the case for other Godot minor versions. 

I'm not sure if using Emscripten has an effect here. You could run
```bash
godot --gdnative-generate-json-api api.json
```
and diff the generated file against the `api.json` in the godot-rust repo.

2022-06-26 20:50 UTC, derivator commented
> ```shell
> godot --gdnative-generate-json-api api.json
> ```

I have no idea how I would do that for a wasm build, but I suspect it's fine. It works for me after all :laughing:

2022-07-02 01:13 UTC, hoodmane commented on src/exporting/html5.md
> +	"-Crelocation-model=pic", # needed to prevent linker errors
This is not needed on nightly Rust:
https://github.com/rust-lang/rust/pull/98149

2022-07-02 01:13 UTC, hoodmane commented on src/exporting/html5.md
> +	"-Cpanic=abort", # panic unwinding is currently broken without -sWASM_BIGINT, see below
PR to fix:
https://github.com/emscripten-core/emscripten/pull/17328

2022-07-04 12:29 UTC, derivator commented on src/exporting/html5.md
> +	"-Cpanic=abort", # panic unwinding is currently broken without -sWASM_BIGINT, see below
I've updated the guide to reflect the current state of affairs.

I initially had some problems where I still needed `-Zbuild-std` (to fix missing ` __cxa_is_pointer_type`) and `-Zlink-native-libraries=no` (to fix `wasm-ld: error: unable to find library -lc`, but after `cargo clean` it works without those flags so maybe rust was incorrectly reusing some old build artifact? @hoodmane can you confirm that these flags shouldn't be needed?

2022-07-04 15:56 UTC, hoodmane commented on src/exporting/html5.md
> +	"-Cpanic=abort", # panic unwinding is currently broken without -sWASM_BIGINT, see below
Currently Pyodide is using:
```
export RUSTFLAGS= \
	-C link-arg=-sSIDE_MODULE=2 \
	-C link-arg=-sWASM_BIGINT \
	-Z link-native-libraries=no
```
https://github.com/pyodide/pyodide/blob/main/Makefile.envs#L159

The problem that `-Zlink-native-libraries=no` fixes is not resolved either on the Rust side or on the Emscripten side. But if it works without it...

2022-07-05 06:28 UTC, jacobsky commented on src/exporting/html5.md
> +**Disclaimer**: _Currently, the following steps are only tested and confirmed to work on Linux._
Fair point. I think keeping a normal disclaimer is probably enough in that case.

2022-07-05 07:39 UTC, Bromeon reviewed
Thanks to you both for the great writeup already! 😊

2022-07-05 07:39 UTC, Bromeon commented on src/exporting/html5.md
> +As of 2022-07-02 you also need to use a Rust nightly build.
Could you maybe specify which features of nightly Rust are needed; is it for the `rustflags` below?

Anything the user needs to specify add in the code, like
```rs
#![feature(some_unstable_thing)]
```

2022-07-05 07:39 UTC, Bromeon commented on src/exporting/html5.md
> +* Emscripten 3.1.16-git (e026c0e22a986d92695b2563a1e8ef140b5d8a87)
This is awesome for reproducibility, thanks a lot! 👍

On which operating system did you test this? Do you think there might be issues on another OS?

2022-07-05 09:47 UTC, derivator commented on src/exporting/html5.md
> +As of 2022-07-02 you also need to use a Rust nightly build.
> Could you maybe specify which features of nightly Rust are needed; is it for the rustflags below?

Previous Rust versions required even more extra flags to get it working, and to build `std` with `-Zbuild-std`, so nightly was required anyway. Thanks to @hoodmane you don't need to build `std` any more on current nightly version, but to my knowledge, it just doesn't work on stable at the moment.

2022-07-05 09:55 UTC, derivator commented on src/exporting/html5.md
> +* Emscripten 3.1.16-git (e026c0e22a986d92695b2563a1e8ef140b5d8a87)
I tested on linux, and the instructions assume you're using a bash-like shell. I don't see an obvious reason why it *wouldn't* work on Windows (Rust, Emscripten, Godot and SCons all work on Windows after all), but I haven't tested it and have no interest in doing so.

2022-07-05 21:59 UTC, Bromeon commented on src/exporting/html5.md
> +* Emscripten 3.1.16-git (e026c0e22a986d92695b2563a1e8ef140b5d8a87)
Makes sense, thanks for the clarification! 🙂

2022-07-05 22:04 UTC, hoodmane commented on src/exporting/html5.md
> +A version mismatch between Rust and Emscripten will probably result in compiler errors, while incompatible Emscripten versions between Rust and Godot will result in cryptic runtime errors such as `in
> will result in cryptic runtime errors such as `indirect call signature mismatch`

It might be worth indicating that `indirect call signature mismatch` does not necessarily mean that there is a version incompatibility: this error message is also the most likely outcome of memory corruption and several other problems.

2022-07-13 08:06 UTC, Bromeon commented on src/exporting/html5.md
> +A version mismatch between Rust and Emscripten will probably result in compiler errors, while incompatible Emscripten versions between Rust and Godot will result in cryptic runtime errors such as `in
@derivator any comment on this? 🙂

2022-08-26 07:08 UTC, Bromeon commented
@derivator @hoodmane Any more comments before this is merged? 🙂

2022-08-26 07:50 UTC, derivator commented
@Bromeon As far as I can tell at a glance, building Godot shouldn't be necessary anymore with Godot 3.5, as the commit that updates their emscripten version seems to have made it in, but I would still keep that information in the guide, in case the same kind of version mismatch happens in the future. I can try updating the guide this weekend.

2022-09-03 09:58 UTC, Bromeon commented
@derivator have you had a chance to look at it yet? 🙂

2022-09-03 17:14 UTC, derivator commented
@Bromeon I'm having a look right now. Some steps will not be necessary anymore, however [Emscripten makes *no* ABI stability promises](https://github.com/emscripten-core/emscripten/blob/main/ChangeLog.md), so while using the export template provided by godot *might* work coincidentally, I think it's probably best to always compile it yourself. I will update the guide to reflect this.

2022-09-04 11:38 UTC, derivator commented
I have it working with Godot 3.5 following the steps in the guide. I believe `-Cpanic=abort` shouldn't be necessary anymore thanks to https://github.com/emscripten-core/emscripten/pull/17328, but I'm still getting errors without it.

2022-09-04 15:30 UTC, merged

2022-09-04 15:31 UTC, Bromeon commented
Thanks a lot to everyone involved! It's great to finally have a bit more resources on the topic of HTML5 exports ❤️

2022-10-02 19:53 UTC, GeTechG commented
I was able to run on emscripten 3.1.14, Godot 3.5.1, rust nightly 0.65.0 (2022-09-03). I was unable to run as suggested on the latest versions of rust and emscripten, or even 3.1.21 as in the tutorial. A runtime error came out with similar text: 
```
at: init_library (modules/gdnative/nativescript/nativescript.cpp:1479) - Condition "lib_path.length() == 0" is true.
```
all because I understood different versions of llvm, so I am puzzled how you could run with the latest version of emscripten, as nightly rust builds still have 15.0, not 16.0.